name: "pre-release"
on:
  push:
    branches:
      - "master"
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@8d9ddb2546e687f72855285d2719a11709cea6d0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: false
          title: "dev"
          files: |
            action.yml
            *.sh